contacts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.contacts, name='contacts'),
    url(r'delete', views.delete, name='delete'),
    url(r'add', views.add, name='add'),
    url(r'edit', views.edit, name='edit'),
]

dz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'dz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^contacts/', include('contacts.urls', namespace="contacts")),
    url(r'^partners/', include('partners.urls', namespace="partners")),
]

managers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.managers, name='managers'),
]

news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

partners/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.partners, name='partners'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^edit/done/$', views.add, name='done'),
] 

presentations/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.presentations, name='presentations'),
]

speakers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.speakers, name='speakers'),
]

contacts/models.py
## -*- coding: utf-8 -*-
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя')
    family = models.CharField(max_length=35, verbose_name='Фамилия')
    phone_number = models.CharField(max_length=20, blank=True, verbose_name='Номер Телефона')
    email = models.EmailField(max_length=30, blank=True, verbose_name='Почта')
    address = models.CharField(max_length=150, blank=True, verbose_name='Адресс')
    def __unicode__(self):
        return self.name

managers/models.py
from django.db import models

class Manager(models.Model):
    name = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    def __unicode__(self):
        return self.name

news/models.py
from django.db import models

class News(models.Model):
    title = models.CharField(max_length=70)
    description = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    text = models.TextField()
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name_plural = "news"

partners/models.py
from django.db import models

class Partner(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=250, blank=True)
    published = models.BooleanField(default=False)
    def __unicode__(self):
        return self.name

presentations/models.py
from django.db import models

class Presentation(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=250, blank=True)
    speaker = models.ForeignKey('speakers.Speaker')
    def __unicode__(self):
        return self.name

speakers/models.py
from django.db import models

class Speaker(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=250, blank=True)
    def __unicode__(self):
        return self.name

partners/forms.py
from django import forms

class AddPartner(forms.Form):
    name = forms.CharField(label="Name", max_length=100)
    description = forms.CharField(max_length=250, required=False, widget=forms.Textarea)
    

contacts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import Contact
from django.http import HttpResponseRedirect

def contacts(request):
    contact_list = Contact.objects.all()
    context = {'contacts':contact_list}
    return render(request, 'contacts/contacts.html', context)


def delete(request):
    cont_id = request.POST['id']
    cont = Contact.objects.get(id = cont_id)
    cont.delete()
    return HttpResponseRedirect("/contacts")
    
    

def add(request):
    post_name = request.POST['name']
    post_family = request.POST['family']
    post_phone = request.POST['phone_number']
    post_email = request.POST['email']
    post_address = request.POST['address']
    New = Contact(name = post_name, family = post_family, phone_number = post_phone, email = post_email, address = post_address)
    New.save()
    return HttpResponseRedirect("/contacts")

def edit(request):
    if request.POST['edited'] == "6":
        post_id = request.POST['id']
        post_name = request.POST['name']
        post_family = request.POST['family']
        post_phone = request.POST['phone_number']
        post_email = request.POST['email']
        post_address = request.POST['address']
        New = Contact(id = post_id, name = post_name, family = post_family, phone_number = post_phone, email = post_email, address = post_address)
        New.save()
        return HttpResponseRedirect("/contacts")
    else:
        post_id = request.POST['id']
        context = {'editable' : Contact.objects.get(id = post_id)}
        return render(request, "contacts/contact_edit.html", context)

managers/views.py
from django.shortcuts import render

news/views.py
from django.shortcuts import render
from .models import News
from django.http import Http404

def index(request):
    news_list = News.objects.all()[:2]
    context = {'news': news_list}
    return render(request, 'news/base_news.html', context)

partners/views.py
from django.shortcuts import render, render_to_response
from .models import Partner
from .forms import AddPartner
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def partners(request):
    partners_list = Partner.objects.all().order_by('name')
    paginator = Paginator(partners_list, 2)
    page = request.GET.get('page')
    try:
        partners_pag = paginator.page(page)
    except PageNotAnInteger:
        partners_pag = paginator.page(1)
    except EmptyPage:
        partners_pag = paginator.page(paginator.num_pages)
    context = {'partners':partners_list,
               'pag':partners_pag,
              }
    return render_to_response('partners/partners.html', context)

def edit(request):
    form = AddPartner()
    return render(request, 'partners/edit.html', {'form':form})

def add(request):
    if request.method == 'POST':
        form = AddPartner(request.POST)
        if form.is_valid():
            p = Partner()
            p.name = form.cleaned_data['name']
            p.description = form.cleaned_data['description']
            p.save()
            return HttpResponseRedirect(reverse('partners:partners'))
    else:
        form = AddPartner()
    return render(request, 'partners/edit.html', {'form':form})
            
    

presentations/views.py
from django.shortcuts import render

# Create your views here.

speakers/views.py
from django.shortcuts import render

# Create your views here.

contacts/templates/contacts/contact_edit.html
{% extends "base.html" %}
{% block content %}
<br><hr>

<form action="/contacts/edit" method="post">
{% csrf_token %}
<input type="hidden" name="edited" value="6"/>
<input type="hidden" name="id" value="{{ editable.id }}"/>
<input type="text" name="name" value="{{ editable.name }}"/><br><br>
<input type="text" name="family" value="{{ editable.family }}"/><br><br>
<input type="text" name="phone_number" value="{{ editable.phone_number }}"/><br><br>
<input type="text" name="email" value="{{ editable.email }}"/><br><br>
<input type="text" name="address" value="{{ editable.address }}"/><br><br>
<input type="submit" value="Сохранить изменения"/>
</form>
{% endblock %}

contacts/templates/contacts/contact_single.html
<h3>{{ contact.name }} {{ contact.family }}</h3>
{{ contact.phone_number }}<br>
{{ contact.email }}<br>
{{ contact.address }}
{%csrf_token %}
<form action="/contacts/delete" method="post">
{% csrf_token %}
<input type="hidden" name="id" value="{{ contact.id }}"/>
<input type="submit" value="Удалить выступление"/>
</form>
<form action="/contacts/edit" method="post">
{% csrf_token %}
<input type="hidden" name="edited" value="1"/>
<input type="hidden" name="id" value="{{ contact.id }}"/>
<input type="submit" value="Редактировать контакт"/>
</form>

contacts/templates/contacts/contacts.html
{% extends "base.html" %}
{% block title %}Contacts{% endblock %}
{% block heading %}Contacts{% endblock %}
{% block content %}
{% for contact in contacts %}
    {% include 'contacts/contact_single.html' %}
{% endfor %}
<br><hr>

<form action="/contacts/add" method="post">
{% csrf_token %}
<input type="text" name="name" value="" placeholder="Введите имя..."><br>
<input type="text" name="family" value="" placeholder="Введите фамилию..."><br>
<input type="text" name="phone_number" value="" placeholder="Введите номер телефона..."><br>
<input type="text" name="email" value="" placeholder="Введите емаил..."><br>
<input type="text" name="address" value="" placeholder="Введите адрес..."><br>
<input type="submit" value="Добавить контакт"/>
</form>
{% endblock %}

news/templates/news/base_news.html
{% extends "base.html" %}
{% block title %}My amazing blog{% endblock %}
{% block content %}
{% for news_item in news %}
 {% include 'news/news_item.html' %}
{% endfor %}
{% endblock %}

news/templates/news/news_item.html
<h2>{{ news_item.title }}</h2>
<p>{{ news_item.description }}</p>

partners/templates/partners/edit.html
{% extends "base.html" %}
{% block title %}Add new partner{% endblock %}
{% block heading %}Add new partner{% endblock %}
{% block sidebar %}{% endblock %}
{% block content %}
<form action="{% url 'partners:done' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add new partner"> 
</form>
{% endblock %}

partners/templates/partners/partner_single.html
<h3 {% if partner.published = True %}style="color:red;"{% endif %}>{{ partner.name|upper }}</h3>
{{ partner.description }}

partners/templates/partners/partners.html
{% extends "base.html" %}
{% block title %}Partners{% endblock %}
{% block heading %}Partners{% endblock %}
{% block content %}
{% for partner in pag.object_list %}
    {% include 'partners/partner_single.html' %}
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if pag.has_previous %}
            <a href="?page={{ pag.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ pag.number }} of {{ pag.paginator.num_pages }}.
        </span>

        {% if pag.has_next %}
            <a href="?page={{ pag.next_page_number }}">next</a>
        {% endif %}
    </span>
</div><br>

<form action="{% url 'partners:edit' %}" method="get">
    <input type="submit" value="Add new partner"> 
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load cache %}
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load staticfiles %}
    {% block style_css %}<link rel="stylesheet" href="{% static 'style.css' %}" />{% endblock %}
 <title>{% block title %}My amazing site{% endblock %}</title>
</head>
<body>
    <div id="heading"><h1>{% block heading %}Index{% endblock %}</h1></div>
 <div id="sidebar">
     {% cache 500 sidebar %}
     {% block sidebar %}
    <ul>
         <li><a href="{% url 'news:index' %}">News</a></li>
         <li><a href="{% url 'contacts:contacts' %}">Contacts</a></li>
         <li><a href="{% url 'partners:partners' %}">Partners</a></li>
         <li><a href="/about/">About</a></li>
    </ul>
     {% endblock %}
     {% endcache %}
 </div>
 <div id="content">
 {% block content %}{% endblock %}
 </div>
</body>
</html>